app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from flask_login import login_required, current_user, login_user, logout_user
from . import db, mail
from .models import User
from .forms import LoginForm, SignUpForm, ResetPasswordForm, RequestResetForm
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.urls import url_parse
from flask_mail import Message


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.hello'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                flash('Вход выполнен!', category='success')
                login_user(user, remember=form.remember_me.data)
                next_page = request.args.get('next')
                if not next_page or url_parse(next_page).netloc != '':
                    next_page = url_for('views.hello')
                return redirect(next_page)
            else:
                flash('Неверный пароль!', category='error')
        else:
            flash('Неверная почта!', category='error')

    return render_template('login.html', user=current_user, form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.hello'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('views.hello'))
    form = SignUpForm()
    if form.validate_on_submit():
        password = form.password.data
        if len(password) < 5:
            flash('Пароль слишком короткий, должен быть длиннее 5 символов!', category='error')
        else:
            new_user = User(email=form.email.data,
                            username=form.username.data,
                            password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            flash('Пользователь создан!')
            return redirect(url_for('views.home'))

    return render_template('signup.html', user=current_user, form=form)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request',

                  recipients=[user.email])
    msg.body = f'''Для сброса пароля пройдите по ссылке:
    {url_for('auth.reset_token', token=token, _external=True)}
    Если Вы не посылали этот запрос, то игнорируйте сообщение.
    '''
    with current_app.open_resource('static/images/1.jpg') as something:
        msg.attach('static/images/1.jpg', 'image/jpeg', something.read())
    mail.send(msg)


@auth.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('views.hello'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Письмо с инструкцией уже отправлено.', category='info')
        return redirect(url_for('auth.login'))
    return render_template('reset_request.html', title='Reset Password', form=form, user=current_user)


@auth.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.hello'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Неправильный токен!', category='warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        user.password = hashed_password
        db.session.add(user)
        db.session.commit()
        flash('Ваш пароль обновлён! Теперь можете войти!', category='success')
        return redirect(url_for('auth.login'))
    return render_template('reset_token.html', form=form, user=current_user)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous">
    <link href="{{ url_for('static', filename='styles.css') }}"
            rel="stylesheet"
            type="text/css">
    <script src="https://kit.fontawesome.com/970a3685a6.js"
            crossorigin="anonymous"></script>

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="d-flex flex-column overflow-hidden min-vh-100 vh-100">
    <header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3" style="background-color: #6f42c1;">
      <div class="container-fluid" >
          <a class="navbar-brand" href="/hello">
          <img src="/static/images/93zGbFI-sakura-blossom-alice-vector.svg" alt="" width="30" height="30" class="d-inline-block align-text-top">Записки королёвского япониста
          </a>
          <div class="navbar-nav">
            <a class="nav-item nav-link active" aria-current="page" href="/home">Блог</a>
          </div>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
              </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbar">
          <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link">{{ current_user.username }}</a>
                <a class="nav-item nav-link" href="/{{current_user.username}}/profile"><img src="{{ current_user.get_avatar(30) }}" width="auto" height="30"></a>
                <a class="nav-item nav-link" href="/logout">Выйти</a>
              {% else %}
                <a class="nav-item nav-link" href="/login">Войти</a>
                <a class="nav-item nav-link" href="/signup">Зарегистрироваться</a>
              {% endif %}
          </div>
        </div>
      </div>
    </nav>
    </header>

    <main role="main" class="flex-grow-1 overflow-auto flex-fill">

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endif %}
                        {% if category == 'success' %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <div class="container">
            {% block content %}

            {% endblock %}
        </div>
    </main>

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top flex-grow-0 sticky-bottom bg-dark">
        <div
        <div class="col-md-4 d-flex align-items-center" >
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <img src="/static/images/009.svg" alt="" width="30" height="30">
          </a>
          <span class="text-muted">© 2021 Записки королёвского япониста</span>
        </div>
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="https://vk.com/vlad.yurkoff"><img src="/static/images/1486147227-social-media-network26_79482.svg" alt="" width="24" height="24" class="d-inline-block align-text-top"></a></li>
          <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/vladislaviurkov72/"><img src="/static/images/Instagram_icon-icons.com_66804.svg" alt="" width="24" height="24" class="d-inline-block align-text-top"></a></li>
          <li class="ms-3"><a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <img src="/static/images/009.svg" alt="" width="30" height="30">
          </a></li>
        </ul>
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
</div>
</body>
</html>

app/templates/create_post.html
{% extends 'base.html' %}

{% block title %} Create new post {% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div >
        <h1 align="center" class="py-3">Новый пост</h1>
    <form method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3 form-group">

          {{ form.text() }}
            {% for error in form.text.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
    </div>
    <div class="d-flex justify-content-center">
    <div >
        <button type="submit" class="btn btn-lg btn-primary">Создать</button>
    </div>
    <div class=" px-3">
        <a href="/home"><button type="button" class="btn btn-secondary">Назад</button></a>
    </div>
        </div>
</form>

</div>
{% endblock %}

app/templates/edit_post.html
{% extends 'base.html' %}

{% block title %} Edit post {% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div >
        <h1 align="center" class="py-3">Редактировать пост</h1>
    <form method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3 form-group">

            {{ form.text() }}
            {% for error in form.text.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
    </div>
    <div class="d-flex justify-content-center">
    <div >
        <button type="submit" class="btn btn-lg btn-primary">Редактировать</button>
    </div>
    <div class=" px-3">
        <a href="/home"><button type="button" class="btn btn-secondary">Назад</button></a>
    </div>
        </div>
</form>

</div>
{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %} Edit profile {% endblock %}

{% block content %}
    <div class="d-flex align-item-center">
        <div><h1>Редактировать профиль</h1></div>
        <div class="px-3 "><a href="/{{ user.username }}/profile" role="button" class="btn btn-sm btn-secondary">
            <i class="fas fa-arrow-left"></i>
        </a></div>
    </div>
    <form method="POST" novalidate>
      {{ form.hidden_tag() }}
      <div class="mb-3 form-group">
          {{ form.email.label }}<br>
          {{ form.email(size=32) }}
          {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </div>
      <div class="mb-3 form-group">
          {{ form.username.label }}<br>
          {{ form.username(size=32) }}
          {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

app/templates/hello.html
{% extends 'base.html' %}

{% block title %} Hello Page {% endblock %}

{% block content %}
    <div class="container">
        <h1 align="center">こんにちは!</h1>
        <h2 align="center">Добро пожаловать!</h2>
        <div align="center">
            <img src="static/images/009.svg" height="30%" width="30%">
        </div>
        <div align="center"><a class="btn" href="/home">Перейти в блог</a></div>
    </div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
{% if user.admin %}
<div  align="center">
    <a href="/create_post"><button type="button" class="btn btn-primary btn-lg">Создать пост</button></a>
</div>
{% endif %}
<br/>
<div class="container md-3 for-post">
{% for post in posts.items %}
    <a name="{{post.id}}"></a>
    <div class="card border-dark" >
        <div class="card-header d-flex justify-content-between align-item-center">
            <div>
            <img src="{{ post.user.get_avatar(30) }}" width="auto" height="30">
            <a href="/{{post.user.username}}/profile" class="btn" role="button">{{post.user.username}}</a>
            </div>
            <div class="d-flex justify-content-end align-item-center my-2">
                <span id="likes-count-{{post.id}}">{{ post.likes|length }}</span>
                {% if user.id in post.likes|map(attribute="author")|list %}
                <i class="fas fa-thumbs-up"
                   id="like-button-{{post.id}}"
                   onclick="like({{post.id}})"></i>
                {% else %}
                <i class="far fa-thumbs-up"
                   id="like-button-{{post.id}}"
                   onclick="like({{post.id}})"></i>
                {% endif %}
                {% if user.id == post.author %}

                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-primary btn-close" data-bs-toggle="dropdown">
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="/delete_post/{{post.id}}" class="dropdown-item">Удалить</a></li>
                    </ul>
                </div>

                {% endif %}
            </div>
        </div>
        <div class="card-body">
            <div class="card-text" style="height: 50px; overflow: hidden;">{{ post.text }}</div>
            <br/>
            <p class="card-text">
                <a role="button" href="{{url_for('views.post', post_id=post.id, page=posts.page)}}" class="btn btn-sm btn-outline-primary">Просмотреть</a>
                {% if post.comments|length > 0 %}
                    <button data-bs-toggle="collapse" role="button"
                       class="btn btn-sm btn-outline-primary" disabled>
                        <small id="comments-button-{{post.id}}"
                                >Комментарии </small>
                        <small id="comments-count-{{post.id}}">({{ post.comments|length }})</small>
                    </button>
                {% else %}
                    <small class="text-muted">Нет комментариев</small>
                {% endif %}
            </p>
            <div class="collapse" id="comments-{{post.id}}">
                <div class="card">
                    <div class="card-body" id="comments-expanded-{{post.id}}">
                        {% for comment in post.comments|reverse %}

                        <div class="d-flex justify-content-between align-items-top">
                            <div class="w-75">
                                    <img src="{{ comment.user.get_avatar(20) }}" width="auto" height="20">
                                    <a href="/{{ comment.user.username }}/profile" class="py-0 px-0">{{ comment.user.username }}</a>
                                : {{ comment.text }}
                            </div>
                            <div align="right">
                                <small class="text-muted">{{ local_time(comment.created_date) }}</small>
                                {% if comment.author == user.id or post.author == user.id %}
                                    <div class="btn-group">
                                        <button type="button"
                                                class="btn btn-sm btn-primary btn-close"
                                                data-bs-toggle="dropdown">
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="/delete_comment/{{comment.id}}" class="dropdown-item">Удалить</a></li>
                                        </ul>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
        <div class="card-footer text-muted">
            {{ local_time(post.created_date) }}
        </div>
    </div>
    <br/>
{% endfor %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center align-item-center">
            <li class="page-item previous{% if not prev_url %} disabled{% endif %} nav-item nav-link">
                <a class="page-link" href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Назад
                </a>
            </li>
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <li class="mx-1 "><a type="button" class="btn btn-sm btn-primary"
                                             href=" {{ url_for('views.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% else %}
                        <li class="mx-1 "><a type="button" class="btn btn-sm btn-outline-primary"
                                             href=" {{ url_for('views.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                    <li>...</li>
                {% endif %}
            {% endfor %}
            <li class="page-item next{% if not next_url %} disabled{% endif %} nav-item nav-link">
                <a class="page-link" href="{{ next_url or '#' }}">
                    Далее <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
    <div><h1>Вход</h1>
    <form method="POST" novalidate>
        {{ form.hidden_tag() }}
      <div class="mb-3 form-group">
          {{ form.email.label }}<br>
          {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
      </div>
      <div class="mb-3 form-group">
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
      </div>
      <div class="mb-3 form-group">
          {{ form.remember_me() }} {{ form.remember_me.label }}
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
      <a href="{{ url_for('auth.reset_request') }}" class="btn btn-sm ">Забыли пароль?</a>
    </form>
        </div>
        </div>
{% endblock %}

app/templates/photo_loader.html
{% extends 'base.html' %}


{% block title %}Загрузка файла{% endblock %}

{% block content %}
  <form enctype="multipart/form-data" method="POST">
   <p>Загрузите аватар</p>
   <p><input type="file" id="photo" name="photo" multiple accept="image/*,image/jpeg">
       <button role="button" type="submit" class="btn btn-primary">Загрузить</button></p>
  </form>
    <a href="/{{user.username}}/profile" role="button" class="btn btn-secondary">Назад</a>
{% endblock %}

</html>

app/templates/post.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="container my-2 for-post">

    <div class="card border-dark">
        <div class="card-header d-flex justify-content-between align-item-center">
            <div>
            <img src="{{ post.user.get_avatar(30) }}" width="auto" height="30">
            <a href="/{{post.user.username}}/profile" class="btn" role="btn">{{post.user.username}}</a>
            </div>
            <div class="d-flex justify-content-end align-item-center my-2">
                <span id="likes-count-{{post.id}}">{{ post.likes|length }}</span>
                {% if user.id in post.likes|map(attribute="author")|list %}
                <i class="fas fa-thumbs-up"
                   id="like-button-{{post.id}}"
                   role="button"
                   onclick="like({{post.id}})"></i>
                {% else %}
                <i class="far fa-thumbs-up"
                   id="like-button-{{post.id}}"
                   role="button"
                   onclick="like({{post.id}})"></i>
                {% endif %}
                {% if user.id == post.author %}
                <div class="px-1">
                    <a href="/{{ post.id }}/edit_post" role="button" ><i class="fas fa-pen-square"></i></a>
                 </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-primary btn-close" data-bs-toggle="dropdown">
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="/delete_post/{{post.id}}" class="dropdown-item">Удалить</a></li>
                    </ul>
                </div>

                {% endif %}
            </div>
        </div>
        <div class="card-body">
            <div class="card-text">{{ post.text }}</div>
            <br/>
            <p class="card-text">
                {% if post.comments|length > 0 %}
                    <a onclick="showComments({{post.id}})"
                                 data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button" class="btn btn-sm btn-outline-primary">
                        <small id="comments-button-{{post.id}}"
                                >Посмотреть комментарии </small>
                        <small id="comments-count-{{post.id}}">({{ post.comments|length }})</small>
                    </a>
                {% else %}
                    <small class="text-muted">Нет комментариев</small>
                {% endif %}
            </p>
            <div class="collapse" id="comments-{{post.id}}">
                <div class="card">
                    <div class="card-body" id="comments-expanded-{{post.id}}">
                        {% for comment in post.comments|reverse %}

                        <div class="d-flex justify-content-between align-items-top" >
                            <div style="width: 90%;">
                                    <img src="{{ comment.user.get_avatar(20) }}" width="auto" height="20">
                                    <a href="/{{ comment.user.username }}/profile" class="py-0 px-0">{{ comment.user.username }}</a>
                                : {{ comment.text }}
                            </div>
                            <div align="right">

                                {% if comment.author == user.id or post.author == user.id %}
                                    <div class="btn-group">
                                        <button type="button"
                                                class="btn btn-sm btn-primary btn-close"
                                                data-bs-toggle="dropdown">
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="/post/{{post.id}}/delete_comment/{{comment.id}}" class="dropdown-item">Удалить</a></li>
                                        </ul>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <small class="text-muted">{{ local_time(comment.created_date) }}</small>
                        <a id="answer-{{comment.id}}" class="btn btn-sm" role="button" onclick="answerComments('{{comment.user.username}}')">Ответить</a>
                        {% endfor %}
                    </div>
                </div>
            </div>

        <form class="mb-1" method="post" action="/create_comment/{{post.id}}" >
            {{ form.hidden_tag() }}
            {{ form.text() }}
            {% for error in form.text.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
            <!-- <input type="text" id="text" name="text" class="form-control" placeholder="Напишите что-нибудь!"/> -->
            <button id="comment-button" type="submit" class="btn btn-primary my-1">Комментировать</button>
        </form>
        </div>
        <div class="card-footer text-muted">
            {{ local_time(post.created_date) }}
        </div>
    </div>
    <br/>
    <div class="d-flex justify-content-center">
    <a href="/home?page={{page}}#{{post.id}}" class="btn btn-secondary">Назад</a>
        {{ page }}
    <button onclick="history.back()">Назад</button>
        </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}
<div class="d-flex justify-content-md-start py-3">
    <img src="{{ user.get_avatar(256) }}" height="auto" width="256">
    <div>
        <div class="d-flex justify-content-md-start ">
            <div>
            <h1 class="px-3">{{ user.username }}</h1>
            <p class="px-3">{{ user.email }}</p>
            </div>
        <div>
            <a href="/{{ user.username }}/edit_profile" role="button" ><i class="fas fa-pen-square"></i></a>
        </div>
        </div>
        <small class="px-3">
            {% if user.is_active %}
                В сети
            {% else %}
                Был в сети: {{ user.last_seen.strftime('%Y.%m.%d %H:%M:%S') }}
            {% endif %}
        </small>
    </div>


</div>
<div>
    <a href="/{{ user.username }}/load_photo" role="button" class="btn btn-sm btn-secondary">Загрузить аватар</a>

</div>
{% endblock %}

app/templates/reset_request.html
{% extends 'base.html' %}

{% block title %} Reset Password {% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
    <div><h1>Сброс пароля</h1>
    <form method="POST" novalidate>
        {{ form.hidden_tag() }}
      <div class="mb-3 form-group">
          {{ form.email.label }}<br>
          {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Отправить запрос</button>
    </form>
        </div>
        </div>
{% endblock %}

app/templates/reset_token.html
{% extends 'base.html' %}

{% block title %} Reset Token {% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
    <div><h1>Сброс пароля</h1>
    <form method="POST" novalidate>
        {{ form.hidden_tag() }}
      <div class="mb-3 form-group">
          {{ form.password.label }}<br>
          {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
      </div>
      <div class="mb-3 form-group">
          {{ form.confirm_password.label }}<br>
          {{ form.confirm_password(size=32) }}
            {% for error in form.confirm_password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
        </div>
        </div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block title %} Sign Up {% endblock %}

{% block content %}
    <div class="d-flex justify-content-center">
    <div><h1>Регистрация</h1>
    <form method="POST" novalidate>
      {{ form.hidden_tag() }}
      <div class="mb-3 form-group">
          {{ form.email.label }}<br>
          {{ form.email(size=32) }}
          {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </div>
      <div class="mb-3 form-group">
          {{ form.username.label }}<br>
          {{ form.username(size=32) }}
          {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </div>
      <div class="mb-3 form-group">
          {{ form.password.label }}<br>
          {{ form.password(size=32) }}
          {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </div>
      <div class="mb-3 form-group">
          {{ form.password2.label }}<br>
          {{ form.password2(size=32) }}
          {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
      </div>
    </div>
{% endblock %}